// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v5.29.2
// source: api/proto/market/v1/market.proto

package marketv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLastTradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticker        string                 `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastTradeRequest) Reset() {
	*x = GetLastTradeRequest{}
	mi := &file_api_proto_market_v1_market_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastTradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastTradeRequest) ProtoMessage() {}

func (x *GetLastTradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_market_v1_market_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastTradeRequest.ProtoReflect.Descriptor instead.
func (*GetLastTradeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_market_v1_market_proto_rawDescGZIP(), []int{0}
}

func (x *GetLastTradeRequest) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

type GetLastTradeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         float64                `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	Size          float64                `protobuf:"fixed64,2,opt,name=size,proto3" json:"size,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Exchange      string                 `protobuf:"bytes,4,opt,name=exchange,proto3" json:"exchange,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastTradeResponse) Reset() {
	*x = GetLastTradeResponse{}
	mi := &file_api_proto_market_v1_market_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastTradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastTradeResponse) ProtoMessage() {}

func (x *GetLastTradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_market_v1_market_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastTradeResponse.ProtoReflect.Descriptor instead.
func (*GetLastTradeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_market_v1_market_proto_rawDescGZIP(), []int{1}
}

func (x *GetLastTradeResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GetLastTradeResponse) GetSize() float64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetLastTradeResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GetLastTradeResponse) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

type GetAggregatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticker        string                 `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Multiplier    int32                  `protobuf:"varint,2,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
	Timespan      string                 `protobuf:"bytes,3,opt,name=timespan,proto3" json:"timespan,omitempty"`
	From          string                 `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"` // Format: YYYY-MM-DD
	To            string                 `protobuf:"bytes,5,opt,name=to,proto3" json:"to,omitempty"`     // Format: YYYY-MM-DD
	Adjusted      bool                   `protobuf:"varint,6,opt,name=adjusted,proto3" json:"adjusted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAggregatesRequest) Reset() {
	*x = GetAggregatesRequest{}
	mi := &file_api_proto_market_v1_market_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAggregatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAggregatesRequest) ProtoMessage() {}

func (x *GetAggregatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_market_v1_market_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAggregatesRequest.ProtoReflect.Descriptor instead.
func (*GetAggregatesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_market_v1_market_proto_rawDescGZIP(), []int{2}
}

func (x *GetAggregatesRequest) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *GetAggregatesRequest) GetMultiplier() int32 {
	if x != nil {
		return x.Multiplier
	}
	return 0
}

func (x *GetAggregatesRequest) GetTimespan() string {
	if x != nil {
		return x.Timespan
	}
	return ""
}

func (x *GetAggregatesRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *GetAggregatesRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *GetAggregatesRequest) GetAdjusted() bool {
	if x != nil {
		return x.Adjusted
	}
	return false
}

type GetAggregatesResponse struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	Bars          []*GetAggregatesResponse_AggregateBar `protobuf:"bytes,1,rep,name=bars,proto3" json:"bars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAggregatesResponse) Reset() {
	*x = GetAggregatesResponse{}
	mi := &file_api_proto_market_v1_market_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAggregatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAggregatesResponse) ProtoMessage() {}

func (x *GetAggregatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_market_v1_market_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAggregatesResponse.ProtoReflect.Descriptor instead.
func (*GetAggregatesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_market_v1_market_proto_rawDescGZIP(), []int{3}
}

func (x *GetAggregatesResponse) GetBars() []*GetAggregatesResponse_AggregateBar {
	if x != nil {
		return x.Bars
	}
	return nil
}

type GetAggregatesResponse_AggregateBar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Open          float64                `protobuf:"fixed64,1,opt,name=open,proto3" json:"open,omitempty"`
	High          float64                `protobuf:"fixed64,2,opt,name=high,proto3" json:"high,omitempty"`
	Low           float64                `protobuf:"fixed64,3,opt,name=low,proto3" json:"low,omitempty"`
	Close         float64                `protobuf:"fixed64,4,opt,name=close,proto3" json:"close,omitempty"`
	Volume        float64                `protobuf:"fixed64,5,opt,name=volume,proto3" json:"volume,omitempty"`
	Vwap          float64                `protobuf:"fixed64,6,opt,name=vwap,proto3" json:"vwap,omitempty"`
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Transactions  int64                  `protobuf:"varint,8,opt,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAggregatesResponse_AggregateBar) Reset() {
	*x = GetAggregatesResponse_AggregateBar{}
	mi := &file_api_proto_market_v1_market_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAggregatesResponse_AggregateBar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAggregatesResponse_AggregateBar) ProtoMessage() {}

func (x *GetAggregatesResponse_AggregateBar) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_market_v1_market_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAggregatesResponse_AggregateBar.ProtoReflect.Descriptor instead.
func (*GetAggregatesResponse_AggregateBar) Descriptor() ([]byte, []int) {
	return file_api_proto_market_v1_market_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetAggregatesResponse_AggregateBar) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *GetAggregatesResponse_AggregateBar) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *GetAggregatesResponse_AggregateBar) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *GetAggregatesResponse_AggregateBar) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *GetAggregatesResponse_AggregateBar) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *GetAggregatesResponse_AggregateBar) GetVwap() float64 {
	if x != nil {
		return x.Vwap
	}
	return 0
}

func (x *GetAggregatesResponse_AggregateBar) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GetAggregatesResponse_AggregateBar) GetTransactions() int64 {
	if x != nil {
		return x.Transactions
	}
	return 0
}

var File_api_proto_market_v1_market_proto protoreflect.FileDescriptor

var file_api_proto_market_v1_market_proto_rawDesc = []byte{
	0x0a, 0x20, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x72, 0x6b,
	0x65, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x6a, 0x61, 0x78, 0x2e, 0x76, 0x31, 0x22, 0x2d, 0x0a, 0x13, 0x47, 0x65,
	0x74, 0x4c, 0x61, 0x73, 0x74, 0x54, 0x72, 0x61, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x22, 0x7a, 0x0a, 0x14, 0x47, 0x65, 0x74,
	0x4c, 0x61, 0x73, 0x74, 0x54, 0x72, 0x61, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x78, 0x63,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x78, 0x63,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x22, 0xaa, 0x01, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x41, 0x67, 0x67,
	0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70,
	0x6c, 0x69, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6d, 0x75, 0x6c, 0x74,
	0x69, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x64, 0x6a, 0x75, 0x73, 0x74,
	0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x61, 0x64, 0x6a, 0x75, 0x73, 0x74,
	0x65, 0x64, 0x22, 0xa6, 0x02, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67,
	0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x04,
	0x62, 0x61, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x6a, 0x61, 0x78,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67,
	0x61, 0x74, 0x65, 0x42, 0x61, 0x72, 0x52, 0x04, 0x62, 0x61, 0x72, 0x73, 0x1a, 0xcc, 0x01, 0x0a,
	0x0c, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x42, 0x61, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x6f, 0x70, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x6f, 0x70, 0x65,
	0x6e, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x67, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x04, 0x68, 0x69, 0x67, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x77, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x03, 0x6c, 0x6f, 0x77, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x76,
	0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x77, 0x61, 0x70, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x04, 0x76, 0x77, 0x61, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x32, 0xac, 0x01, 0x0a, 0x0d,
	0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4b, 0x0a,
	0x0c, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x54, 0x72, 0x61, 0x64, 0x65, 0x12, 0x1b, 0x2e,
	0x6a, 0x61, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x54, 0x72,
	0x61, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x6a, 0x61, 0x78,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x54, 0x72, 0x61, 0x64, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x0d, 0x47, 0x65,
	0x74, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x73, 0x12, 0x1c, 0x2e, 0x6a, 0x61,
	0x78, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6a, 0x61, 0x78, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x6b, 0x69, 0x6e, 0x6f, 0x6c, 0x69,
	0x6b, 0x2f, 0x6a, 0x61, 0x78, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2f, 0x76, 0x31, 0x3b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_market_v1_market_proto_rawDescOnce sync.Once
	file_api_proto_market_v1_market_proto_rawDescData = file_api_proto_market_v1_market_proto_rawDesc
)

func file_api_proto_market_v1_market_proto_rawDescGZIP() []byte {
	file_api_proto_market_v1_market_proto_rawDescOnce.Do(func() {
		file_api_proto_market_v1_market_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_market_v1_market_proto_rawDescData)
	})
	return file_api_proto_market_v1_market_proto_rawDescData
}

var file_api_proto_market_v1_market_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_market_v1_market_proto_goTypes = []any{
	(*GetLastTradeRequest)(nil),                // 0: jax.v1.GetLastTradeRequest
	(*GetLastTradeResponse)(nil),               // 1: jax.v1.GetLastTradeResponse
	(*GetAggregatesRequest)(nil),               // 2: jax.v1.GetAggregatesRequest
	(*GetAggregatesResponse)(nil),              // 3: jax.v1.GetAggregatesResponse
	(*GetAggregatesResponse_AggregateBar)(nil), // 4: jax.v1.GetAggregatesResponse.AggregateBar
}
var file_api_proto_market_v1_market_proto_depIdxs = []int32{
	4, // 0: jax.v1.GetAggregatesResponse.bars:type_name -> jax.v1.GetAggregatesResponse.AggregateBar
	0, // 1: jax.v1.MarketService.GetLastTrade:input_type -> jax.v1.GetLastTradeRequest
	2, // 2: jax.v1.MarketService.GetAggregates:input_type -> jax.v1.GetAggregatesRequest
	1, // 3: jax.v1.MarketService.GetLastTrade:output_type -> jax.v1.GetLastTradeResponse
	3, // 4: jax.v1.MarketService.GetAggregates:output_type -> jax.v1.GetAggregatesResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_market_v1_market_proto_init() }
func file_api_proto_market_v1_market_proto_init() {
	if File_api_proto_market_v1_market_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_market_v1_market_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_market_v1_market_proto_goTypes,
		DependencyIndexes: file_api_proto_market_v1_market_proto_depIdxs,
		MessageInfos:      file_api_proto_market_v1_market_proto_msgTypes,
	}.Build()
	File_api_proto_market_v1_market_proto = out.File
	file_api_proto_market_v1_market_proto_rawDesc = nil
	file_api_proto_market_v1_market_proto_goTypes = nil
	file_api_proto_market_v1_market_proto_depIdxs = nil
}
