// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: api/proto/confluence/v1/confluence.proto

package confluencev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfluenceService_GetConfluence_FullMethodName        = "/jax.v1.ConfluenceService/GetConfluence"
	ConfluenceService_GetConfluenceSummary_FullMethodName = "/jax.v1.ConfluenceService/GetConfluenceSummary"
	ConfluenceService_WatchConfluence_FullMethodName      = "/jax.v1.ConfluenceService/WatchConfluence"
)

// ConfluenceServiceClient is the client API for ConfluenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ConfluenceService exposes real-time multi-signal confluence scores for day trading.
type ConfluenceServiceClient interface {
	// GetConfluence returns the latest snapshot for a ticker, activating the ticker if needed.
	GetConfluence(ctx context.Context, in *GetConfluenceRequest, opts ...grpc.CallOption) (*ConfluenceSnapshot, error)
	// GetConfluenceSummary returns a human-readable summary projected from the latest snapshot.
	GetConfluenceSummary(ctx context.Context, in *GetConfluenceRequest, opts ...grpc.CallOption) (*ConfluenceSummary, error)
	// WatchConfluence streams snapshot updates when score or signal status changes.
	WatchConfluence(ctx context.Context, in *WatchConfluenceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConfluenceSnapshot], error)
}

type confluenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConfluenceServiceClient(cc grpc.ClientConnInterface) ConfluenceServiceClient {
	return &confluenceServiceClient{cc}
}

func (c *confluenceServiceClient) GetConfluence(ctx context.Context, in *GetConfluenceRequest, opts ...grpc.CallOption) (*ConfluenceSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfluenceSnapshot)
	err := c.cc.Invoke(ctx, ConfluenceService_GetConfluence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *confluenceServiceClient) GetConfluenceSummary(ctx context.Context, in *GetConfluenceRequest, opts ...grpc.CallOption) (*ConfluenceSummary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfluenceSummary)
	err := c.cc.Invoke(ctx, ConfluenceService_GetConfluenceSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *confluenceServiceClient) WatchConfluence(ctx context.Context, in *WatchConfluenceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConfluenceSnapshot], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConfluenceService_ServiceDesc.Streams[0], ConfluenceService_WatchConfluence_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchConfluenceRequest, ConfluenceSnapshot]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConfluenceService_WatchConfluenceClient = grpc.ServerStreamingClient[ConfluenceSnapshot]

// ConfluenceServiceServer is the server API for ConfluenceService service.
// All implementations must embed UnimplementedConfluenceServiceServer
// for forward compatibility.
//
// ConfluenceService exposes real-time multi-signal confluence scores for day trading.
type ConfluenceServiceServer interface {
	// GetConfluence returns the latest snapshot for a ticker, activating the ticker if needed.
	GetConfluence(context.Context, *GetConfluenceRequest) (*ConfluenceSnapshot, error)
	// GetConfluenceSummary returns a human-readable summary projected from the latest snapshot.
	GetConfluenceSummary(context.Context, *GetConfluenceRequest) (*ConfluenceSummary, error)
	// WatchConfluence streams snapshot updates when score or signal status changes.
	WatchConfluence(*WatchConfluenceRequest, grpc.ServerStreamingServer[ConfluenceSnapshot]) error
	mustEmbedUnimplementedConfluenceServiceServer()
}

// UnimplementedConfluenceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfluenceServiceServer struct{}

func (UnimplementedConfluenceServiceServer) GetConfluence(context.Context, *GetConfluenceRequest) (*ConfluenceSnapshot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfluence not implemented")
}
func (UnimplementedConfluenceServiceServer) GetConfluenceSummary(context.Context, *GetConfluenceRequest) (*ConfluenceSummary, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfluenceSummary not implemented")
}
func (UnimplementedConfluenceServiceServer) WatchConfluence(*WatchConfluenceRequest, grpc.ServerStreamingServer[ConfluenceSnapshot]) error {
	return status.Errorf(codes.Unimplemented, "method WatchConfluence not implemented")
}
func (UnimplementedConfluenceServiceServer) mustEmbedUnimplementedConfluenceServiceServer() {}
func (UnimplementedConfluenceServiceServer) testEmbeddedByValue()                           {}

// UnsafeConfluenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfluenceServiceServer will
// result in compilation errors.
type UnsafeConfluenceServiceServer interface {
	mustEmbedUnimplementedConfluenceServiceServer()
}

func RegisterConfluenceServiceServer(s grpc.ServiceRegistrar, srv ConfluenceServiceServer) {
	// If the following call pancis, it indicates UnimplementedConfluenceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfluenceService_ServiceDesc, srv)
}

func _ConfluenceService_GetConfluence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfluenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfluenceServiceServer).GetConfluence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfluenceService_GetConfluence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfluenceServiceServer).GetConfluence(ctx, req.(*GetConfluenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfluenceService_GetConfluenceSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfluenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfluenceServiceServer).GetConfluenceSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfluenceService_GetConfluenceSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfluenceServiceServer).GetConfluenceSummary(ctx, req.(*GetConfluenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfluenceService_WatchConfluence_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchConfluenceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConfluenceServiceServer).WatchConfluence(m, &grpc.GenericServerStream[WatchConfluenceRequest, ConfluenceSnapshot]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConfluenceService_WatchConfluenceServer = grpc.ServerStreamingServer[ConfluenceSnapshot]

// ConfluenceService_ServiceDesc is the grpc.ServiceDesc for ConfluenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfluenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jax.v1.ConfluenceService",
	HandlerType: (*ConfluenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfluence",
			Handler:    _ConfluenceService_GetConfluence_Handler,
		},
		{
			MethodName: "GetConfluenceSummary",
			Handler:    _ConfluenceService_GetConfluenceSummary_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchConfluence",
			Handler:       _ConfluenceService_WatchConfluence_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/confluence/v1/confluence.proto",
}
